name: iconocracy
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - jupyter
  - matplotlib
  - numpy
  - psycopg2
  - pylint
  - pip
  - pip:
    - jsonschema>=4.23,<5
    - referencing>=0.35,<1
    - rpds-py>=0.20,<1
    - rich>=10.0
    - prince
    - statsmodels
    - seaborn
    - scipy
    - scikit-posthocs
