#!/usr/bin/env python3
"""
Auto Issue Creator — Monitors error logs and creates GitHub issues when errors repeat N times.

Usage:
    python auto_issue.py [--log FILE] [--threshold N] [--dry-run]
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional


@dataclass
class ErrorOccurrence:
    """Represents a single error occurrence."""
    timestamp: datetime
    error_type: str
    message: str
    traceback: Optional[str] = None


@dataclass
class ErrorPattern:
    """Aggregated error pattern with multiple occurrences."""
    signature: str
    count: int
    first_seen: datetime
    last_seen: datetime
    occurrences: List[ErrorOccurrence]
    
    @property
    def title(self) -> str:
        if len(self.signature) > 80:
            return f"{self.signature[:77]}..."
        return self.signature
    
    @property
    def body(self) -> str:
        lines = [
            "## Error Summary",
            "",
            f"**Pattern:** `{self.signature}`",
            f"**Occurrences:** {self.count}",
            f"**First seen:** {self.first_seen.isoformat()}",
            f"**Last seen:** {self.last_seen.isoformat()}",
            "",
            "## Recent Occurrences",
            "",
        ]
        
        for i, occ in enumerate(self.occurrences[-3:], 1):
            lines.append(f"### Occurrence {i}")
            lines.append(f"**Time:** {occ.timestamp.isoformat()}")
            lines.append(f"**Message:** {occ.message}")
            if occ.traceback:
                lines.append("```")
                lines.append(occ.traceback)
                lines.append("```")
            lines.append("")
        
        lines.extend([
            "## Suggested Actions",
            "",
            "- [ ] Reproduce the error",
            "- [ ] Identify root cause",
            "- [ ] Implement fix",
            "- [ ] Add test case",
            "",
            "---",
            "_Auto-generated by `tools/scripts/auto_issue.py`_"
        ])
        
        return "\n".join(lines)


class ErrorParser:
    TRACEBACK_START = re.compile(r'^Traceback \(most recent call last\):')
    ERROR_LINE = re.compile(r'^(\w+Error): (.+)$')
    TIMESTAMP_PATTERN = re.compile(r'(\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2})')
    
    @staticmethod
    def extract_signature(error_type: str, message: str) -> str:
        cleaned = re.sub(r'/[^\s]+', '/PATH', message)
        cleaned = re.sub(r'\d{4,}', 'ID', cleaned)
        cleaned = re.sub(r'\b\d+\.\d+\b', 'NUM', cleaned)
        return f"{error_type}: {cleaned}"
    
    def parse_log(self, log_path: Path, window_hours: int = 24) -> List[ErrorOccurrence]:
        cutoff = datetime.now() - timedelta(hours=window_hours)
        errors: List[ErrorOccurrence] = []
        
        if not log_path.exists():
            return errors
        
        with log_path.open('r', encoding='utf-8', errors='ignore') as f:
            lines = f.readlines()
        
        i = 0
        while i < len(lines):
            line = lines[i].rstrip()
            ts_match = self.TIMESTAMP_PATTERN.search(line)
            timestamp = datetime.fromisoformat(ts_match.group(1).replace(' ', 'T')) if ts_match else datetime.now()
            
            if timestamp < cutoff:
                i += 1
                continue
            
            if self.TRACEBACK_START.search(line):
                traceback_lines = [line]
                i += 1
                
                while i < len(lines):
                    tb_line = lines[i].rstrip()
                    traceback_lines.append(tb_line)
                    error_match = self.ERROR_LINE.match(tb_line)
                    if error_match:
                        errors.append(ErrorOccurrence(
                            timestamp=timestamp,
                            error_type=error_match.group(1),
                            message=error_match.group(2),
                            traceback='\n'.join(traceback_lines)
                        ))
                        i += 1
                        break
                    i += 1
            else:
                i += 1
        
        return errors


class IssueCreator:
    @staticmethod
    def check_gh_available() -> bool:
        try:
            subprocess.run(['gh', '--version'], capture_output=True, check=True)
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False
    
    @staticmethod
    def issue_exists(pattern_signature: str) -> bool:
        try:
            result = subprocess.run(
                ['gh', 'issue', 'list', '--search', f'"{pattern_signature}" in:title', '--json', 'number'],
                capture_output=True, text=True, check=True
            )
            issues = json.loads(result.stdout)
            return len(issues) > 0
        except (subprocess.CalledProcessError, json.JSONDecodeError):
            return False
    
    @staticmethod
    def create_issue(pattern: ErrorPattern, dry_run: bool = False) -> Optional[str]:
        if dry_run:
            print(f"\n{'='*80}")
            print(f"DRY RUN: Would create issue:")
            print(f"Title: {pattern.title}")
            print(f"\n{pattern.body}")
            print(f"{'='*80}\n")
            return None
        
        try:
            result = subprocess.run(
                ['gh', 'issue', 'create', 
                 '--title', pattern.title,
                 '--body', pattern.body,
                 '--label', 'bug,auto-generated'],
                capture_output=True, text=True, check=True
            )
            return result.stdout.strip()
        except subprocess.CalledProcessError as e:
            print(f"Error creating issue: {e.stderr}", file=sys.stderr)
            return None


def main() -> None:
    parser = argparse.ArgumentParser(description="Monitor error logs and create GitHub issues.")
    parser.add_argument('--log', type=Path, default=Path('logs/errors.log'))
    parser.add_argument('--threshold', type=int, default=3)
    parser.add_argument('--window', type=int, default=24)
    parser.add_argument('--dry-run', action='store_true')
    args = parser.parse_args()
    
    if not args.dry_run and not IssueCreator.check_gh_available():
        print("Error: gh CLI not found", file=sys.stderr)
        sys.exit(1)
    
    error_parser = ErrorParser()
    occurrences = error_parser.parse_log(args.log, args.window)
    
    if not occurrences:
        print(f"No errors in {args.log} within last {args.window}h")
        return
    
    patterns: Dict[str, ErrorPattern] = defaultdict(lambda: ErrorPattern(
        signature="", count=0, first_seen=datetime.max,
        last_seen=datetime.min, occurrences=[]
    ))
    
    for occ in occurrences:
        sig = ErrorParser.extract_signature(occ.error_type, occ.message)
        pattern = patterns[sig]
        pattern.signature = sig
        pattern.count += 1
        pattern.first_seen = min(pattern.first_seen, occ.timestamp)
        pattern.last_seen = max(pattern.last_seen, occ.timestamp)
        pattern.occurrences.append(occ)
    
    creator = IssueCreator()
    created = skipped = 0
    
    for pattern in patterns.values():
        if pattern.count < args.threshold:
            continue
        if not args.dry_run and creator.issue_exists(pattern.signature):
            print(f"Issue exists: {pattern.signature}")
            skipped += 1
            continue
        url = creator.create_issue(pattern, args.dry_run)
        if url:
            print(f"✓ Created: {url}")
        created += 1
    
    print(f"\nTotal: {len(patterns)} | Created: {created} | Skipped: {skipped}")


if __name__ == '__main__':
    main()
