#!/usr/bin/env python3
"""
Sync companion app data from corpus-data.json and vault ZW panels.

Reads the canonical corpus and vault, generates updated JS data for
the iconocracia-companion dashboard.

Usage:
    python tools/scripts/sync_companion.py [--output path/to/companion-data.js]
"""

import json
import re
import sys
from pathlib import Path
from collections import Counter

REPO = Path(__file__).resolve().parent.parent.parent
CORPUS = REPO / "corpus" / "corpus-data.json"
VAULT_C = REPO / "vault" / "candidatos"
VAULT_S = REPO / "vault" / "sessoes"

# Map corpus country names to codes
COUNTRY_MAP = {
    "France": "FR", "Brazil": "BR", "United States": "US",
    "Germany": "DE", "United Kingdom": "UK", "Belgium": "BE",
    "Netherlands": "NL", "Portugal": "PT", "Italy": "IT",
    "Austria": "AT", "Spain": "ES", "Switzerland": "CH",
    "Uruguay": "UY", "Mexico": "MX",
}

COUNTRY_NAMES = {
    "FR": "França", "BR": "Brasil", "US": "Estados Unidos",
    "DE": "Alemanha", "UK": "Reino Unido", "BE": "Bélgica",
    "NL": "Países Baixos", "PT": "Portugal", "IT": "Itália",
}

COUNTRY_FLAGS = {
    "FR": "🇫🇷", "BR": "🇧🇷", "US": "🇺🇸", "DE": "🇩🇪",
    "UK": "🇬🇧", "BE": "🇧🇪", "NL": "🇳🇱", "PT": "🇵🇹",
}


def load_corpus():
    with open(CORPUS) as f:
        return json.load(f)


def count_by_country(items):
    counts = Counter()
    for item in items:
        code = COUNTRY_MAP.get(item.get("country", ""), "?")
        counts[code] += 1
    return counts


def count_vault_notes():
    """Count SCOUT- notes and coded items in vault."""
    candidates = list(VAULT_C.glob("SCOUT-[0-9]*.md"))
    negative = list(VAULT_C.glob("SCOUT-NC-*.md"))
    panels = list(VAULT_C.glob("SCOUT-ZW-*.md"))
    sessions = list(VAULT_S.glob("SCOUT-SESSION-*.md"))
    return {
        "candidates": len(candidates),
        "negative_controls": len(negative),
        "zwischenraum_panels": len(panels),
        "sessions": len(sessions),
        "total_vault": len(candidates) + len(negative) + len(panels),
    }


def extract_zw_panels():
    """Extract Zwischenraum panel data from vault notes."""
    panels = []
    for f in sorted(VAULT_C.glob("SCOUT-ZW-*.md")):
        text = f.read_text()
        # Extract frontmatter
        title_match = re.search(r'titulo:\s*"(.+?)"', text)
        pais_match = re.search(r'pais:\s*\[(.+?)\]', text)
        periodo_match = re.search(r'periodo:\s*"(.+?)"', text)
        id_match = re.search(r'id:\s*(SCOUT-ZW-\d+)', text)

        panels.append({
            "id": id_match.group(1) if id_match else f.stem,
            "title": title_match.group(1) if title_match else f.stem,
            "countries": [c.strip() for c in pais_match.group(1).split(",")] if pais_match else [],
            "period": periodo_match.group(1) if periodo_match else "",
            "file": f.name,
        })
    return panels


def generate_companion_data(items):
    """Generate JS-compatible data object."""
    by_country = count_by_country(items)
    vault = count_vault_notes()
    panels = extract_zw_panels()

    countries = []
    for code in ["FR", "US", "DE", "BR", "NL", "UK", "BE", "PT", "IT"]:
        if by_country.get(code, 0) > 0:
            countries.append({
                "code": code,
                "name": COUNTRY_NAMES.get(code, code),
                "flag": COUNTRY_FLAGS.get(code, "🏳️"),
                "items": by_country[code],
                "coded": 0,  # to be updated when IconoCode runs
            })

    data = {
        "generated": "auto-generated by sync_companion.py",
        "corpus_total": len(items),
        "vault": vault,
        "countries": countries,
        "zwischenraum_panels": panels,
    }
    return data


def main():
    output = Path(sys.argv[2]) if len(sys.argv) > 2 and sys.argv[1] == "--output" else None

    items = load_corpus()
    data = generate_companion_data(items)

    result = json.dumps(data, indent=2, ensure_ascii=False)

    if output:
        output.write_text(result)
        print(f"Written to {output}")
    else:
        print(result)

    # Summary
    print(f"\n--- Companion Sync Summary ---", file=sys.stderr)
    print(f"Corpus items: {data['corpus_total']}", file=sys.stderr)
    print(f"Countries: {len(data['countries'])}", file=sys.stderr)
    print(f"Vault candidates: {data['vault']['candidates']}", file=sys.stderr)
    print(f"ZW panels: {data['vault']['zwischenraum_panels']}", file=sys.stderr)
    print(f"Sessions: {data['vault']['sessions']}", file=sys.stderr)


if __name__ == "__main__":
    main()
