#!/usr/bin/env python3
"""
Sync companion app data from corpus-data.json and vault ZW panels.

Reads the canonical corpus and vault, generates updated data for
the iconocracia-companion dashboard.

Usage:
    python tools/scripts/sync_companion.py                          # print JSON
    python tools/scripts/sync_companion.py --output data.json       # save to file
    python tools/scripts/sync_companion.py --push URL               # PUT to companion API
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from collections import Counter

REPO = Path(__file__).resolve().parent.parent.parent
CORPUS = REPO / "corpus" / "corpus-data.json"
VAULT_C = REPO / "vault" / "candidatos"
VAULT_S = REPO / "vault" / "sessoes"

# Map corpus country names to codes
COUNTRY_MAP = {
    "France": "FR", "Brazil": "BR", "United States": "US",
    "Germany": "DE", "United Kingdom": "UK", "Belgium": "BE",
    "Netherlands": "NL", "Portugal": "PT", "Italy": "IT",
    "Austria": "AT", "Spain": "ES", "Switzerland": "CH",
    "Uruguay": "UY", "Mexico": "MX",
}

COUNTRY_NAMES = {
    "FR": "França", "BR": "Brasil", "US": "Estados Unidos",
    "DE": "Alemanha", "UK": "Reino Unido", "BE": "Bélgica",
    "NL": "Países Baixos", "PT": "Portugal", "IT": "Itália",
}

COUNTRY_FLAGS = {
    "FR": "🇫🇷", "BR": "🇧🇷", "US": "🇺🇸", "DE": "🇩🇪",
    "UK": "🇬🇧", "BE": "🇧🇪", "NL": "🇳🇱", "PT": "🇵🇹",
}


def load_corpus():
    with open(CORPUS) as f:
        return json.load(f)


def count_by_country(items):
    counts = Counter()
    for item in items:
        code = COUNTRY_MAP.get(item.get("country", ""), "?")
        counts[code] += 1
    return counts


def count_vault_notes():
    """Count SCOUT- notes and coded items in vault."""
    candidates = list(VAULT_C.glob("SCOUT-[0-9]*.md"))
    negative = list(VAULT_C.glob("SCOUT-NC-*.md"))
    panels = list(VAULT_C.glob("SCOUT-ZW-*.md"))
    sessions = list(VAULT_S.glob("SCOUT-SESSION-*.md"))
    return {
        "candidates": len(candidates),
        "negative_controls": len(negative),
        "zwischenraum_panels": len(panels),
        "sessions": len(sessions),
        "total_vault": len(candidates) + len(negative) + len(panels),
    }


def extract_zw_panels():
    """Extract Zwischenraum panel data from vault notes."""
    panels = []
    for f in sorted(VAULT_C.glob("SCOUT-ZW-*.md")):
        text = f.read_text()
        # Extract frontmatter
        title_match = re.search(r'titulo:\s*"(.+?)"', text)
        pais_match = re.search(r'pais:\s*\[(.+?)\]', text)
        periodo_match = re.search(r'periodo:\s*"(.+?)"', text)
        id_match = re.search(r'id:\s*(SCOUT-ZW-\d+)', text)

        panels.append({
            "id": id_match.group(1) if id_match else f.stem,
            "title": title_match.group(1) if title_match else f.stem,
            "countries": [c.strip() for c in pais_match.group(1).split(",")] if pais_match else [],
            "period": periodo_match.group(1) if periodo_match else "",
            "file": f.name,
        })
    return panels


def generate_companion_data(items):
    """Generate JS-compatible data object."""
    by_country = count_by_country(items)
    vault = count_vault_notes()
    panels = extract_zw_panels()

    countries = []
    for code in ["FR", "US", "DE", "BR", "NL", "UK", "BE", "PT", "IT"]:
        if by_country.get(code, 0) > 0:
            countries.append({
                "code": code,
                "name": COUNTRY_NAMES.get(code, code),
                "flag": COUNTRY_FLAGS.get(code, "🏳️"),
                "items": by_country[code],
                "coded": 0,  # to be updated when IconoCode runs
            })

    data = {
        "generated": "auto-generated by sync_companion.py",
        "corpus_total": len(items),
        "vault": vault,
        "countries": countries,
        "zwischenraum_panels": panels,
    }
    return data


def push_to_companion(base_url, corpus_data, atlas_data=None):
    """Push data to companion API endpoints."""
    try:
        import urllib.request
    except ImportError:
        print("ERRO: urllib not available", file=sys.stderr)
        return False

    # Push corpus data
    corpus_url = f"{base_url.rstrip('/')}/api/corpus"
    req = urllib.request.Request(
        corpus_url, method="PUT",
        data=json.dumps(corpus_data).encode(),
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"Corpus pushed: {resp.status}", file=sys.stderr)
    except Exception as e:
        print(f"Corpus push failed: {e}", file=sys.stderr)
        return False

    # Push atlas data if available
    if atlas_data:
        atlas_url = f"{base_url.rstrip('/')}/api/atlas"
        req = urllib.request.Request(
            atlas_url, method="PUT",
            data=json.dumps(atlas_data).encode(),
            headers={"Content-Type": "application/json"},
        )
        try:
            with urllib.request.urlopen(req) as resp:
                print(f"Atlas pushed: {resp.status}", file=sys.stderr)
        except Exception as e:
            print(f"Atlas push failed: {e}", file=sys.stderr)

    return True


def main():
    output = None
    push_url = None

    args = sys.argv[1:]
    while args:
        arg = args.pop(0)
        if arg == "--output" and args:
            output = Path(args.pop(0))
        elif arg == "--push" and args:
            push_url = args.pop(0)

    items = load_corpus()
    data = generate_companion_data(items)
    result = json.dumps(data, indent=2, ensure_ascii=False)

    # Load atlas mapping if available
    atlas_file = REPO / "corpus" / "atlas-mapping.json"
    atlas_data = json.loads(atlas_file.read_text()) if atlas_file.exists() else None

    if output:
        output.write_text(result)
        print(f"Written to {output}", file=sys.stderr)
    elif push_url:
        push_to_companion(push_url, data, atlas_data)
    else:
        print(result)

    # Summary
    print(f"\n--- Companion Sync Summary ---", file=sys.stderr)
    print(f"Corpus items: {data['corpus_total']}", file=sys.stderr)
    print(f"Countries: {len(data['countries'])}", file=sys.stderr)
    print(f"Vault candidates: {data['vault']['candidates']}", file=sys.stderr)
    print(f"ZW panels: {data['vault']['zwischenraum_panels']}", file=sys.stderr)
    print(f"Sessions: {data['vault']['sessions']}", file=sys.stderr)


if __name__ == "__main__":
    main()
