name = "iconocracia-companion"
main = "src/index.js"
compatibility_date = "2026-03-20"

[assets]
directory = "./public"

[[kv_namespaces]]
binding = "DIARY_KV"
id = "17d97b88cc3f4461b1f99b64e167bad5"
