name: iconocracy-local
values:
  - key: baseUrl
    value: 'http://localhost:8787'
    enabled: true
    type: default
  - key: diarySecret
    value: ''
    enabled: true
    type: default
  - key: attr
    value: ''
    enabled: true
    type: default
  - key: figure
    value: ''
    enabled: true
    type: default
  - key: country
    value: ''
    enabled: true
    type: default
  - key: regime
    value: ''
    enabled: true
    type: default
  - key: q
    value: ''
    enabled: true
    type: default
  - key: itemId
    value: ''
    enabled: true
    type: default
